markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
# domain: www.panxw.com
title: Thornbird's Blog
description: 
author: thornbird
email: wuhanzaizai#126.com
github: bjfuzzj

config:
  js_dir:
  img_dir:
  css_dir:
