markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
highlighter: pygments
#safe: true
gems: [jekyll-paginate]
paginate: 8
paginate_path: "page:num/"

# presonal config
# domain: www.panxw.com
title: Thornbird Blog
description: 
author: thornbird
email: wuhanzaizai#126.com
github: bjfuzzj

config:
  js_dir:
  img_dir:
  css_dir:
